version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE=project: ${PROJECT}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - ${MONGOEXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}

      # if admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: '${MONGO_ROOT_USERNAME}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '${MONGO_ROOT_PASSWORD}'

      #else
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      # ME_CONFIG_MONGODB_AUTH_DATABASE: ${PROJECT}
      # ME_CONFIG_MONGODB_AUTH_USERNAME: '${MONGO_ROOT_USERNAME}'
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: '${MONGO_ROOT_PASSWORD}'

      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - ./data:/data/db
