version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '{REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data:/data
volumes:
  redis:
    driver: local
